---

- name: Download needed container images
  containers.podman.podman_image:
    name: "{{ edpm_logrotate_crond_image }}"
    auth_file: "{{ edpm_podman_auth_file | default() }}"
  become: true
  register: edpm_logrotate_crond_cronie_images_download
  until: edpm_logrotate_crond_cronie_images_download.failed == false
  retries: "{{ edpm_logrotate_crond_download_retries }}"
  delay: "{{ edpm_logrotate_crond_download_delay }}"
